---
- hosts: all
  become: yes

  tasks:
    - name: collect facts about system services
      service_facts:
      register: services_state
  tasks:
    - name: Print service facts
      ansible.builtin.debug:
      var: ansible_facts.services