---
- name: Execute shell script on remote server
  hosts: all
  tasks:
    - name: Copy shell script to remote server
      copy:
        src: /etc/hi.sh
        dest: /etc/hi.sh
        mode: 0755

    - name: Run shell script on remote server
      shell: sh /etc/hi.sh

    - name: Remove shell script from remote server
      file:
        path: /etc/hi.sh
        state: absent