---
- hosts: all
  become: yes

  tasks:
  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
      reboot_timeout: 60
      msg: "Rebooting machine in 60 seconds"