---
- hosts: all
  become: yes

  tasks:
  - name: Reboot server
    shell: reboot
    async: 0
    poll: 0

  - name: Wait for the machine to come back online
    wait_for_connection:
    connect_timeout: 60
    sleep: 5
    delay: 5
    timeout: 300